### ISSUE TITLE
SYNC-71 ⁃ FxaException - JSON error invalid type: expected unit variant PushPayload::Unknown

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/uniffi-rs#115]
When messages are being delivered from push to fxaclient, I was seeing this intially in my logs:

```
2019-10-05 01:39:11.409 11625-11789/org.mozilla.reference.browser.debug E/FxaDeviceConstellation: Error while running: processing raw events
    mozilla.appservices.fxaclient.FxaException$Unspecified: JSON error: invalid type: map, expected unit variant PushPayload::Unknown at line 1 column 61
        at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:48)
        at mozilla.appservices.fxaclient.FirefoxAccount.handlePushMessage(FirefoxAccount.kt:802)
        at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEventAsync$1$1.invoke(FxaDeviceConstellation.kt:72)
        at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEventAsync$1$1.invoke(FxaDeviceConstellation.kt:34)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$5.invoke(Utils.kt:64)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$5.invoke(Unknown Source:0)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:30)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:56)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:63)
        at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEventAsync$1.invokeSuspend(FxaDeviceConstellation.kt:71)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
		
2019-10-05 01:39:38.496 12864-12898/? E/FxADeviceListUpdater: Error while getting the FxA device list.
    java.net.SocketTimeoutException: failed to connect to api.accounts.firefox.com/34.218.72.173 (port 443) from /192.168.0.37 (port 43909) after 30000ms
        at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
        at libcore.io.IoBridge.connect(IoBridge.java:135)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:156)
        at ch.boye.httpclientandroidlib.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:524)
        at ch.boye.httpclientandroidlib.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
        at ch.boye.httpclientandroidlib.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
        at ch.boye.httpclientandroidlib.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
        at ch.boye.httpclientandroidlib.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
        at ch.boye.httpclientandroidlib.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
        at ch.boye.httpclientandroidlib.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
        at ch.boye.httpclientandroidlib.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
        at ch.boye.httpclientandroidlib.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.mozilla.gecko.sync.net.BaseResource.execute(BaseResource.java:312)
        at org.mozilla.gecko.sync.net.BaseResource.retryRequest(BaseResource.java:353)
        at org.mozilla.gecko.sync.net.BaseResource.execute(BaseResource.java:322)
        at org.mozilla.gecko.sync.net.BaseResource.go(BaseResource.java:377)
        at org.mozilla.gecko.sync.net.BaseResource.get(BaseResource.java:383)
        at org.mozilla.gecko.background.fxa.FxAccountClient20.deviceList(FxAccountClient20.java:897)
        at org.mozilla.gecko.fxa.devices.FxAccountDeviceListUpdater.update(FxAccountDeviceListUpdater.java:121)
        at org.mozilla.gecko.fxa.FxAccountPushHandler.handleDeviceDisconnection(FxAccountPushHandler.java:122)
        at org.mozilla.gecko.fxa.FxAccountPushHandler.handleFxAPushMessage(FxAccountPushHandler.java:52)
        at org.mozilla.gecko.push.PushService.handleMessage(PushService.java:468)
        at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:368)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at org.mozilla.gecko.util.GeckoBackgroundThread.run(GeckoBackgroundThread.java:41)
```

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-71)

**Comment by data-sync-user** [comment]
➤ Edouard Oger commented:

Assuming you can reproduce this reliably, do you know which payload is being sent to FirefoxAccount.handlePushMessage?
