### ISSUE TITLE
SYNC-102 ⁃ "Sync now" failing with "mozilla.appservices.places.PlacesException: A connection of this type is already open"

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/uniffi-rs#123]
I hit this in a local build of Fenix and haven't yet been able to reproduce, but wanted to file for followup. What happened was basically:

* Made a local build of Fenix against the new v0.31.3 release of appservices.
* Launched it on an emulator.
* Signed in with my Firefox Account.
* Waited a bit, then went to see if my bookmarks had been synced; they hadn't.
* Attempted a "sync now" to force bookmarks to sync; it appeared to succeed but the bookmarks didn't appear.
* Went to logcat to investigate and found several instances of this in `adb logcat | grep -i bookmarks`:

```
07-03 14:54:11.266  5707  5750 D PlacesBookmarksStorage: Syncing...
07-03 14:54:11.266  5707  5750 D places_ffi: sync15_bookmarks_sync
07-03 14:54:11.267  5707  5750 E PlacesBookmarksStorage: Places exception while syncing
07-03 14:54:11.267  5707  5750 E PlacesBookmarksStorage: mozilla.appservices.places.PlacesException: A connection of this type is already open
07-03 14:54:11.267  5707  5750 E PlacesBookmarksStorage:        at mozilla.appservices.places.RustError.intoException(RustError.kt:58)
07-03 14:54:11.267  5707  5750 E PlacesBookmarksStorage:        at mozilla.appservices.places.PlacesApi.syncBookmarks(PlacesConnection.kt:948)
07-03 14:54:11.267  5707  5750 E PlacesBookmarksStorage:        at mozilla.components.browser.storage.sync.RustPlacesConnection.syncBookmarks(Connection.kt:193)
07-03 14:54:11.267  5707  5750 E PlacesBookmarksStorage:        at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$sync$2.invokeSuspend(PlacesBookmarksStorage.kt:183)
07-03 14:54:11.267  5707  5750 E PlacesBookmarksStorage:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-03 14:54:11.267  5707  5750 E PlacesBookmarksStorage:        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
07-03 14:54:11.267  5707  5750 E PlacesBookmarksStorage:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
07-03 14:54:11.267  5707  5750 E PlacesBookmarksStorage:        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
07-03 14:54:11.267  5707  5750 E PlacesBookmarksStorage:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
07-03 14:54:11.275  5707  5750 E StorageSync: Error synchronizing a bookmarks store
07-03 14:54:11.275  5707  5750 E StorageSync:   at mozilla.appservices.places.PlacesApi.syncBookmarks(PlacesConnection.kt:948)
07-03 14:54:11.275  5707  5750 E StorageSync:   at mozilla.components.browser.storage.sync.RustPlacesConnection.syncBookmarks(Connection.kt:193)
07-03 14:54:11.275  5707  5750 E StorageSync:   at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$sync$2.invokeSuspend(PlacesBookmarksStorage.kt:183)
07-03 14:54:11.285  5707  5750 E SyncWorker: Failed to synchronize store bookmarks
07-03 14:54:11.285  5707  5750 E SyncWorker:    at mozilla.appservices.places.PlacesApi.syncBookmarks(PlacesConnection.kt:948)
07-03 14:54:11.285  5707  5750 E SyncWorker:    at mozilla.components.browser.storage.sync.RustPlacesConnection.syncBookmarks(Connection.kt:193)
07-03 14:54:11.285  5707  5750 E SyncWorker:    at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$sync$2.invokeSuspend(PlacesBookmarksStorage.kt:183)                 
```

Exiting and restarting Fenix appeared to unstick it. So far I haven't been able to reproduce.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-102)

**Comment by data-sync-user** [comment]
➤ Thom Chiovoloni commented:

Almost certainly two attempts to open the same PlacesApi. This will end up with two copies of the same Arc<PlacesApi> inside our FFI layer, and allow concurrent access to these functions. Which is fine, but definitely a bug (probably on the Fenix or A-C side)

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I have the full adb logcat output of this if it will be useful for debugging, and can share via email.  In particular, logging at the full log I see that my very first error was a mozilla.appservices.places.PlacesConnectionBusy: Error executing SQL: database is locked while syncing history:

07-03 14:54:11.184  5707  6107 I sync15::sync: Sync finished!
07-03 14:54:11.184  5707  6107 I sync15::sync_multiple: Sync of history was successful!
07-03 14:54:11.184  5707  6107 I sync15::sync_multiple: Updating persisted global state
07-03 14:54:11.184  5707  6107 D sync15::sync_multiple: sync was successful, final status=Ok
07-03 14:54:11.232  5707  6139 D places_ffi: places_note_observation
07-03 14:54:11.241  5707  6036 D places_ffi: sync15_history_sync
07-03 14:54:11.256  5707  6036 E places::ffi: Database busy: Error { code: DatabaseBusy, extended_code: 5 } Some("database is locked")
07-03 14:54:11.258  5707  6036 E PlacesHistoryStorage: Places exception while syncing
07-03 14:54:11.258  5707  6036 E PlacesHistoryStorage: mozilla.appservices.places.PlacesConnectionBusy: Error executing SQL: database is locked Which might have contributed to getting into this bad state.
