### ISSUE TITLE
Runtime exception when constructing UDL defined interface with procmacro async methods

### ISSUE THREAD

**Issue by stan-irl** [mozilla/uniffi-rs#1570]
I have an empty interface defined in UDL. This interface has a number of procmacro defined async methods on it. When I try and call the ctor in kotlin I get a runtime error: `java.lang.IllegalArgumentException: Callback must implement a single public method, or one public method named 'callback'`

My code is roughly as follows:

UDL:

```
interface Foo{};
```

lib.rs:

```
#[uniffi::export]
impl Foo {
    pub async fn bar(&self) -> Result<String, Error> {
        ...
    }
}
```

And the full error looks like this:

```
Caused by: java.lang.IllegalArgumentException: Callback must implement a single public method, or one public method named 'callback'
		at com.sun.jna.CallbackReference.getCallbackMethod(CallbackReference.java:418)
		at com.sun.jna.CallbackReference.getCallbackMethod(CallbackReference.java:388)
		at com.sun.jna.CallbackReference.<init>(CallbackReference.java:283)
		at com.sun.jna.CallbackReference.getFunctionPointer(CallbackReference.java:506)
		at com.sun.jna.CallbackReference.getFunctionPointer(CallbackReference.java:483)
		at com.sun.jna.Function.convertArgument(Function.java:558)
		at com.sun.jna.Function.invoke(Function.java:345)
		at com.sun.jna.Library$Handler.invoke(Library.java:265)
		at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
		at $Proxy8.uniffi_foreign_executor_callback_set(Unknown Source)
```

Is this bug in the library?  I made sure I'm using the same JNA version and kotlin-coroutines as you are in [your tests](https://github.com/mozilla/uniffi-rs/blob/1851fef86d001e0264c8268cdb559d1eb82bee3e/fixtures/futures/examples/kotlin/Makefile#L1-L3).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-275)
┆Issue Number: UNIFFI-275

**Comment by stan-irl** [comment]
@Hywan do you have any idea what would cause this?

**Comment by badboy** [comment]
> @bendk

Hey,

(I'm not Ben). Sometimes answers take a bit of time. There's usually no need to ping individuals within hours of opening an issue.

**Comment by stan-irl** [comment]
@badboy sorry im not trying to be annoying. ben asked me to open an issue in matrix. this was more of an FYI tag in response to that

**Comment by bendk** [comment]
I tested it out in https://github.com/bendk/uniffi-rs/tree/async-methods-test and it seemed to work for me.  Does the `fixtures/futures` test pass for you?

**Comment by stan-irl** [comment]
My company just went under because 95% of our users are bots so I probably wont be able to make you a repro 🤣 

Closing this now
