### ISSUE TITLE
Android: `java.lang.ClassNotFoundException: Didn't find class "*UniffiRustFutureContinuationCallback"`

### ISSUE THREAD

**Issue by jmartinesp** [mozilla/uniffi-rs#1998]
I was doing some experiments with UniFFi and when trying to test them against our project using the main branch I got:

```
 E  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.matrix.rustcomponents.sdk.UniffiRustFutureContinuationCallback" on path: ... // Very long dex path list here
    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	... 37 more
```

If seems to happen after commit d4c38acc07224e3af48acc2c8a2d29aec7b92362, the previous one works just fine.

I can see the `UniffiRustFutureContinuationCallback` is actually now part of the generated bindings, but for some reason it's not really working on our side:

```kotlin
package org.matrix.rustcomponents.sdk;

// Rest of the bindings file...

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: USize,`pollResult`: Byte,)
}
```

I didn't test it on a pure JVM environment, but I guess it probably works fine since the tests of the project work. The Android device I used has Android 14, in case it's important.

**Comment by jmartinesp** [comment]
Ah sorry, I didn't realise it's a dupe of https://github.com/mozilla/uniffi-rs/issues/1995. Although in our case it's happening as soon as the app starts and the lib is loaded, not on instrumented tests.

**Comment by jmartinesp** [comment]
FWIW, renaming the `internal object uniffiRustFutureContinuationCallback` seems to fix the issue. I tried just adding a `_` prefix to it and the app worked fine with the code in the `main` branch again. Could it be an issue with case insensitive file systems somehow?
