### ISSUE TITLE
`Lift` / `LiftRef` error with bad compilation error for large enums

### ISSUE THREAD

**Issue by Sajjon** [mozilla/uniffi-rs#2041]
Follow-up [on thread on Matrix](https://matrix.to/#/!tsNDDGHvNGVNmvOOzi:mozilla.org/$pRoFZYH9at1LGsmrliYwSsKBj9JardJ513vvp3w9WgQ?via=mozilla.org&via=matrix.org&via=element.io) with @mhammond 

This fairly large (107 cases) error enum (see [source here]()https://github.com/radixdlt/sargon/blob/develop/src/core/error/common_error.rs#L10):

```rust
#[repr(u32)]
#[derive(Clone, Debug, ThisError, PartialEq, uniffi::Error)]
#[uniffi(flat_error)]
pub enum CommonError2 {
 // 106 cases omitted
    #[error("String not hex '{bad_value}'")]
    StringNotHex { bad_value: String } = 10011,
}
```

results in UniFFI unable to compile when I add a `#[uniffi::export]`-ed function taking the error enum as argument:
```rust
#[uniffi::export]
pub fn error_message_from_error(error: &CommonError2) -> String {
    format!("{}", error)
}
```

I suspect this method triggers the `LiftRef` to be used, which has not been used before. **To be clear, I'm already using the error enum, it has been UniFFI converted to Swift and Kotlin and I have tested using bindgen methods returning (throwing) the error, and that works...**. But UniFFI gets sad when I write Rust code requiring LIFT (and I suspect LOWER).

The compilation error is not very informative, it does not say what has failed, or at least I don't understand it...:

```sh
error[E0277]: the trait bound `common_error::CommonError2: LiftRef<UniFfiTag>` is not satisfied
   --> src/core/error/common_error.rs:789:1
    |
789 | #[uniffi::export]
    | ^^^^^^^^^^^^^^^^^ the trait `LiftRef<UniFfiTag>` is not implemented for `common_error::CommonError2`
    |
    = help: the following other types implement trait `LiftRef<UT>`:
              <bool as LiftRef<UT>>
              <i8 as LiftRef<UT>>
              <i16 as LiftRef<UT>>
              <i32 as LiftRef<UT>>
              <i64 as LiftRef<UT>>
              <u8 as LiftRef<UT>>
              <u16 as LiftRef<UT>>
              <u32 as LiftRef<UT>>
            and 215 others
    = note: this error originates in the attribute macro `uniffi::export` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `common_error::CommonError2: LiftRef<UniFfiTag>` is not satisfied
   --> src/core/error/common_error.rs:790:41
    |
790 | pub fn error_message_from_error(error: &CommonError2) -> String {
    |                                         ^^^^^^^^^^^^ the trait `LiftRef<UniFfiTag>` is not implemented for `common_error::CommonError2`
    |
    = help: the following other types implement trait `LiftRef<UT>`:
              <bool as LiftRef<UT>>
              <i8 as LiftRef<UT>>
              <i16 as LiftRef<UT>>
              <i32 as LiftRef<UT>>
              <i64 as LiftRef<UT>>
              <u8 as LiftRef<UT>>
              <u16 as LiftRef<UT>>
              <u32 as LiftRef<UT>>
            and 215 others

For more information about this error, try `rustc --explain E0277`.
error: could not compile `sargon` (lib test) due to 2 previous errors
```

Ok.. too bad. Then I tried removing `#[uniffi(flat_error)]`, then I get a much better error message: `assert!(self.size < BUF_SIZE)`:

```sh
error[E0080]: evaluation of constant value failed
   --> /Users/sajjon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi_core-0.26.1/src/metadata.rs:143:9
    |
143 |         assert!(self.size < BUF_SIZE);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: self.size < BUF_SIZE', /Users/sajjon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi_core-0.26.1/src/metadata.rs:143:9
    |
note: inside `MetadataBuffer::concat_value`
   --> /Users/sajjon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi_core-0.26.1/src/metadata.rs:143:9
    |
143 |         assert!(self.size < BUF_SIZE);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `MetadataBuffer::concat_bool`
   --> /Users/sajjon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi_core-0.26.1/src/metadata.rs:169:9
    |
169 |         self.concat_value(value as u8)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `UNIFFI_META_CONST_SARGON_ERROR_COMMONERROR2`
   --> src/core/error/common_error.rs:396:46
    |
396 | #[derive(Clone, Debug, ThisError, PartialEq, uniffi::Error)]
    |                                              ^^^^^^^^^^^^^
    = note: this error originates in the macro `assert` which comes from the expansion of the derive macro `uniffi::Error` (in Nightly builds, run with -Z macro-backtrace for more info)
```

So I guess the error enum is too large? 

(Still without `#[uniffi(flat_error)]`)  I tried commenting out first half of the 107 cases, and then it everything works! And then I tried the second half (to see if it was any specific case which broke LiftRef...), and it worked to! 

Conclusion: it is indeed the size of the enum...?

My goal here is to have a single enum for all error, being flat so that I can get compile guarantees that the discriminants are indeed globally unique. 

Is it possible to lift (pun intended) the restriction of 4096 `BUF_SIZE`, as in increase that size? 

Or can I decrease the size of my error enum by removing the associated values perhaps? They are not as important as being able to have many many hundreds of error cases with a (globally unique) discriminant.

**Comment by Sajjon** [comment]
Interesting, no worries at all if I use `Lift` instead of `LiftRef` **with** `#[uniffi(flat_error)]`

```rust
#[repr(u32)]
#[derive(Clone, Debug, ThisError, PartialEq, uniffi::Error)]
#[uniffi(flat_error)] // <-- Only works with `flat_error`
pub enum CommonError {
    #[error("Unknown Error")]
    Unknown = 10000,

   // 106 other cases ommitted
}

// N.B. not using `&` for `CommonError` below!
#[uniffi::export]
pub fn error_message_from_error(error: CommonError) -> String { 
    format!("{}", error)
}
```

But if I remove `#[uniffi(flat_error)]`, I get the BUF_SIZE error again.

```
3 |         assert!(self.size < BUF_SIZE);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: self.size < BUF_SIZE', /Users/sajjon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi_core-0.26.1/src/metadata.rs:143:9
    |
note: inside `MetadataBuffer::concat_value`
   --> /Users/sajjon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi_core-0.26.1/src/metadata.rs:143:9
    |
143 |         assert!(self.size < BUF_SIZE);
```

**Comment by mhammond** [comment]
Is this still reproducible now #2042 has landed?

**Comment by Sajjon** [comment]
@mhammond closed as completed. Thx for reminding me!
