### ISSUE TITLE
v0.27.0 regression of `uniffi-bindgen generate`

### ISSUE THREAD

**Issue by CatStudioApp** [mozilla/uniffi-rs#2057]
```
  [rstarget] git:(main) ✗ /Users/[user]/Developer/[proj]/[app]/[rstarget]/target/debug/uniffi-bindgen generate --lib-file ../target/aarch64-apple-ios-sim/debug/lib[rstarget].dylib src/[rstarget].udl --language swift -o ../tmp/
thread 'main' panicked at /Users/[user]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi-0.27.0/src/lib.rs:33:21:
called `Result::unwrap()` on an `Err` value: missing field `package` at line 51 column 1

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/backtrace.rs:331:13
   3: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /Users/[user]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.81/src/error.rs:565:25
   4: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/result.rs:1959:27
   5: uniffi_bindgen::crate_name_from_cargo_toml
             at /Users/[user]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi_bindgen-0.27.0/src/lib.rs:359:22
   6: uniffi_bindgen::generate_external_bindings::{{closure}}
             at /Users/[user]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi_bindgen-0.27.0/src/lib.rs:234:28
   7: core::option::Option<T>::unwrap_or_else
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/option.rs:976:21
   8: uniffi_bindgen::generate_external_bindings
             at /Users/[user]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi_bindgen-0.27.0/src/lib.rs:232:22
   9: uniffi_bindgen::generate_bindings
             at /Users/[user]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi_bindgen-0.27.0/src/lib.rs:316:5
  10: uniffi::cli::run_main
             at /Users/[user]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi-0.27.0/src/cli.rs:115:17
  11: uniffi::uniffi_bindgen_main
             at /Users/[user]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi-0.27.0/src/lib.rs:33:5
  12: uniffi_bindgen::main
             at ./uniffi-bindgen/src/main.rs:2:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/ops/function.rs:250:5
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/sys_common/backtrace.rs:155:18
  15: std::rt::lang_start::{{closure}}
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/rt.rs:166:18
  16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/ops/function.rs:284:13
  17: std::panicking::try::do_call
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:554:40
  18: std::panicking::try
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:518:19
  19: std::panic::catch_unwind
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panic.rs:142:14
  20: std::rt::lang_start_internal::{{closure}}
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/rt.rs:148:48
  21: std::panicking::try::do_call
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:554:40
  22: std::panicking::try
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:518:19
  23: std::panic::catch_unwind
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panic.rs:142:14
  24: std::rt::lang_start_internal
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/rt.rs:148:20
  25: std::rt::lang_start
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/rt.rs:165:17
  26: _main
stack backtrace:
   0: rust_begin_unwind
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/result.rs:1073:23
   4: uniffi::uniffi_bindgen_main
             at /Users/[user]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi-0.27.0/src/lib.rs:33:5
   5: uniffi_bindgen::main
             at ./uniffi-bindgen/src/main.rs:2:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by CatStudioApp** [comment]
thanks for your reply!

any suggestions on getting the details?
I already use `RUST_BACKTRACE=full`

**Comment by badboy** [comment]
The backtrace is ok, but we don't know what code you run uniffi-bindgen on

**Comment by imWildCat** [comment]
ok let me create a minimal reproducible example project

**Comment by CatStudioApp** [comment]
@badboy I suspect https://github.com/mozilla/uniffi-rs/pull/2061 is related.

I can say this problem has been fixed in the latest version
