### ISSUE TITLE
How to catch an exception on rust side?

### ISSUE THREAD

**Issue by augustocdias** [mozilla/uniffi-rs#2231]
We're exposing a callback through the FFI that returns a `Result<(), Error>`. If in kotlin side for example an exception is thrown inside this callback, how to properly handle it on rust side?

example:

on rust side we have:

```rust
#[uniffi::export(with_foreign)]
#[async_trait::async_trait]
pub trait CoreCryptoCommand: std::fmt::Debug + Send + Sync {
    /// Will be called inside a transaction in CoreCrypto
    async fn execute(&self, context: Arc<CoreCryptoContext>) -> Result<(), CCError>;
}

#[derive(uniffi::Object)]
pub struct CoreCryptoContext {
    context: Context,
}

#[uniffi::export]
impl CoreCrypto {
    pub async fn transaction(&self, command: Arc<dyn CoreCryptoCommand>) -> Result<(), CCError> {
        let context = Arc::new(CoreCryptoContext {
            context: self.central.new_context().await,
        });
        let result = command.execute(context.clone()).await;
        println!("commiting");
        if result.is_ok() {
            context.context.finish().await;
        }
        result
    }
}
```

and on kotlin side:

```kotlin
cc.transaction(object: CoreCryptoCommand {
   override suspend fun execute(ctx: CoreCryptoContext) {
           throw RuntimeException("What should happen here?")
   }
})
```

When I execute this, I get the following exception:

```
uniffi.core_crypto.InternalException: UnexpectedUniFFICallbackError(reason: "java.lang.RuntimeException: What should happen here?")
        at uniffi.core_crypto.Core_cryptoKt.uniffiCheckCallStatus(core_crypto.kt:275)
        at uniffi.core_crypto.Core_cryptoKt.access$uniffiCheckCallStatus(core_crypto.kt:1)
        at uniffi.core_crypto.Core_cryptoKt.uniffiRustCallAsync(core_crypto.kt:2113)
        at uniffi.core_crypto.Core_cryptoKt$uniffiRustCallAsync$1.invokeSuspend(core_crypto.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at Test.<init>(test.kts:17)
```

How could I properly handle this in the rust side? I was expecting that here `let result = command.execute(context.clone()).await;` I'd get a result with the error inside.

**Comment by augustocdias** [comment]
I have just found out I have to implement `From<uniffi::UnexpectedUniFFICallbackError>` to do what I want. 

Sorry for the noise
