### ISSUE TITLE
Unhandled expection while connection is lost while loging in

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/uniffi-rs#731]
If at some point between calling `finishAuthenticationAsync` and the authentication finishes, the internet connection is lost there is an uncaught exception:

```
2019-11-07 14:19:38.682 6067-6216/org.mozilla.vrbrowser.dev E/GeckoCrashHandler: >>> REPORTING UNCAUGHT EXCEPTION FROM THREAD 325 ("pool-7-thread-1")
    kotlin.KotlinNullPointerException
        at mozilla.components.service.fxa.manager.FxaAccountManager.postAuthenticated(FxaAccountManager.kt:873)
        at mozilla.components.service.fxa.manager.FxaAccountManager$postAuthenticated$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-11-07 14:19:38.683 6067-6216/org.mozilla.vrbrowser.dev E/GeckoCrashHandler: Main thread (2) stack:
```

**Comment by data-sync-user** [comment]
➤ Edouard Oger commented:

This is probably a question for Android Components, grigoryk what do you think?
