### ISSUE TITLE
PushManager: java.lang.IllegalMonitorStateException: unlock of unowned monitor on object of type '(raw)'

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/uniffi-rs#830]
We're seeing an unusual error from (what I understand) the raw pointer for the PushManager. The kicker: this is only happening on x86 devices running on Android 5.x. :smile: 

Sentry link: https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9261958/

```
java.lang.IllegalMonitorStateException: unlock of unowned monitor on object of type '(raw)' on thread 'Thread[27,tid=16507,Runnable,Thread*=0xf4225100,peer=0x28803800,"pool-11-thread-1"]'
    at mozilla.appservices.push.PushManager.<init>(PushManager.kt:10)
    at mozilla.components.feature.push.RustPushConnection.updateToken(Connection.kt:15)
    at mozilla.components.feature.push.AutoPushFeature$$special$$inlined$let$lambda$1.invokeSuspend(AutoPushFeature.kt:6)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)

mozilla.components.concept.push.PushError$Rust: unlock of unowned monitor on object of type '(raw)' on thread 'Thread[27,tid=16507,Runnable,Thread*=0xf4225100,peer=0x28803800,"pool-11-thread-1"]'
    at mozilla.components.feature.push.AutoPushFeature$$special$$inlined$exceptionHandler$1.handleException(CoroutineExceptionHandler.kt:5)
    at androidx.core.app.AppOpsManagerCompat.handleCoroutineException(AppOpsManagerCompat.java:2)
    at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:1)
    at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:13)
    at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:16)
    at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:11)
    at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:2)
    at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:1)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:11)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

I'm not sure that this is a server bug.
Push messages are usually specified as JSON, so not sure what '(raw)' refers to. I don't know of any part of the incoming message named "raw". Also, The first half of the report identifies it as PushManager.kt:10 which seems VERY early in the file. (FWIW, line 10 in PushManager.kt is

import java.util.LocaleI have no idea if kotlin does some sort of code run on import like python or something.

This also looks like it's a token update call, which happens at around line 95.

**Comment by data-sync-user** [comment]
➤ Jonathan Almeida commented:

I don't think it's a server bug either, rather a bug in the layer between the native rust code and the kotlin.

I think we use a raw pointer to reference the Kotlin PushManager in app services.

Not sure how much of that is accurate though, since I'm going on many hypothetical cases here.

**Comment by data-sync-user** [comment]
➤ Jonathan Almeida commented:

> The first half of the report identifies it as PushManager.kt:10 which seems VERY early in the file. (FWIW, line 10 in PushManager.kt is
> 
> ```
> import java.util.Locale
> ```

The stack trace shows relative numbers when it comes from Sentry since this is compiled bytecode that has no reference to the line numbers in file. So line 10 is relative to the init function (block) in this case. It should be this line ( https://github.com/mozilla/application-services/blob/main/components/push/android/src/main/java/mozilla/appservices/push/PushManager.kt#L41 ) which is the end of the call to create a new push connection.

init {
    try {
        handle.set(rustCall { error ->
            LibPushFFI.INSTANCE.push_connection_new(
                    serverHost,
                    httpProtocol,
                    bridgeType.toString(),
                    registrationId,
                    senderId,
                    databasePath,
                    error)
        })
    } catch (e: InternalPanic) {
        // Do local error handling?

throw e
    }
}

**Comment by data-sync-user** [comment]
➤ Jonathan Almeida commented:

As Fenix rolls out to release, the affected users have slowly started to rise although they are still only x86 and Android 5.x users so far which are a very niche group, as I can tell.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

That handle.set is operating on an AtomicLong, which may be relevant if this is some sort of locking-related issue.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I also see some similar issues that appear related to Glean: https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9294817/

**Comment by data-sync-user** [comment]
➤ Jonathan Almeida commented:

This number has been increasing as more users are migrating. rfk will this be triaged?

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

TBH, I think we're just scratching our heads about what a possible next step here could be :-(

I see this has the "discuss" label so it should come up in our next synchronous triage, but I'll try to remember to raise it if it doesn't appear automatically.

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

Looking to see if I could find the source of that error, I found this reference ( https://android.googlesource.com/platform/art/+/master/runtime/monitor.cc#701 ) which implies that the object isn't owned by the thread that's trying to access it, presumably to mutate it. Granted, that's not a whole lot of help. I could maybe understand if there was a reference being send over the FFI (none that I can tell) or maybe an unwrap().clone() failing weirdly inside of the rust layer. It might(?) be worth running that code through a newer version of clippy to see if it spots anything that could be cleaned up a bit. 

I'd also be interested in seeing if this issue happens on only specific versions of Android OS in case it's an OS error.

**Comment by data-sync-user** [comment]
➤ Jonathan Almeida commented:

> I'd also be interested in seeing if this issue happens on only specific versions of Android OS in case it's an OS error.

All the errors are limited to x86 builds running Android 5.x which is the oldest OS version we support.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

We discussed this a little in the team meeting today, I don't think we're any closer to understanding what's happening here but some thoughts below for context.

The error message seems pretty clear that this is an error happening in Java-land, not inside the rust code. The fact that it's being reported as a PushError$Rust instance seems likely to be due to generic wrapping of exceptions in this class, as seen e.g. here ( https://github.com/mozilla-mobile/android-components/blob/d3732b0ca54a3575c50a3249ef468e51d204f565/components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt#L363 ).

The special string (raw) in the error message looks like a placeholder value used when the system can't find the class of the object ( https://android.googlesource.com/platform/art/+/master/runtime/mirror/object.cc#288 ) that it's trying to print.

This all seems to be running on single-threaded executor (ref here ( https://github.com/mozilla-mobile/android-components/blob/d3732b0ca54a3575c50a3249ef468e51d204f565/components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt#L71 )) so I don't think we can blame it on operations completing on a different thread to where they were initiated.

We also see a similar error appearing for other rust-based APIs, such as the one linked above for glean, or this one ( https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9302617 ) for creating a PlacesApi. They all seem to happen at the same point, inside the constructor for the Kotlin-side rust wrapper class around the point where we try to store the rust object handle into an AtomicLong. So I think this is likely to be something generic in the way we're bridging from Kotlin to Rust, not something specific to the Push component.

One possibility, which I hate to even suggest...maybe there's a bug in AtomicLong on older android devices, perhaps when interacting with co-routines, and we're triggering it? I don't know, and I don't really know how to find out from here :-/

I expect we're going to really struggle to debug this unless we're able to reproduce it. jonalmeida do you know if we've anyone with access to an x86/Android 5.x device who might have a hope of reproducing?

We could also try some speculative fixes here, for example we could replace the use of AtomicLong with a more explicit Mutex, ship it, and see if the crashes reduce. Not pretty, but I'm kind of grasping at straws here.

I wonder if native-code-on-android experts from other teams such as GeckoView have any other suggestions here.

**Comment by data-sync-user** [comment]
➤ Grisha Kruglov commented:

Volume of this has been going down (I'm guessing, as these 5.0 devices, tablets mostly, are dying off):
https://user-images.githubusercontent.com/465422/104551723-44cf2100-55ec-11eb-9d65-af2cde96d1a5.png
