### ISSUE TITLE
SYNC-1491 ⁃ [Push] push::crypto - base64 failed for target:salt; InvalidByte(0, 34)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/uniffi-rs#88]
Similar to https://github.com/mozilla/application-services/issues/3364, we're seeing this error pop-up now.

```
mozilla.components.support.rustlog.RustErrorException: push::crypto - base64 failed for target:salt; InvalidByte(0, 34)
    at mozilla.components.support.rustlog.CrashReporterOnLog.invoke(RustLog.kt:11)
    at mozilla.appservices.rustlog.RawLogCallbackImpl.invoke(RustLogAdapter.kt:3)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:11)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:1)
    at com.sun.jna.Native.invokePointer(Native.java)
    at com.sun.jna.Function.invokePointer(Function.java:1)
    at com.sun.jna.Function.invoke(Function.java:60)
    at com.sun.jna.Function.invoke(Function.java:22)
    at com.sun.jna.Library$Handler.invoke(Library.java:27)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy6.push_decrypt
    at mozilla.appservices.push.PushManager.decrypt(PushManager.kt:5)
    at mozilla.components.feature.push.RustPushConnection.decryptMessage(Connection.kt:5)
    at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$$inlined$ifInitialized$lambda$1.invokeSuspend(AutoPushFeature.kt:12)
    at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$$inlined$ifInitialized$lambda$1.invoke
    at mozilla.components.feature.push.ext.CoroutineScopeKt$launchAndTry$2.invokeSuspend(CoroutineScope.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
```

Sentry:

* https://sentry.prod.mozaws.net/operations/fenix/issues/8820593/

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1491)

**Comment by data-sync-user** [comment]
➤ Jonathan Almeida commented:

cc: @jrconlin

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

There was a release approximate to when this error started being reported, but it was to fix metric calls:
https://github.com/mozilla-services/autopush/releases/tag/1.56.2

I'm guessing that the message body is not present, which would trigger the length error. If the body is, indeed, present, there could be an error in how the padding is applied, but I'm not sure if that's required for the client library.

**Comment by data-sync-user** [comment]
➤ Jonathan Almeida commented:

I updated the Sentry link and title because I had wrongly duplicated it from the other issue.

Copying over the same comment from that issue: these showed up recently because we started to forward the errors to the crash reporter which we were not doing before.

So I imagine they might have been happening before the mentioned updates without us noticing them.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

> base64 failed for target:salt; InvalidByte(0, 34)

According to the `base64` crate docs ( https://docs.rs/base64/0.12.3/base64/enum.DecodeError.html ), the arguments to InvalidByte here are the offset of the character being decoded, and the byte value that failed to decode.  Byte 34 is the ASCII double-quote character ". So IIUC this is failing because it found a double-quote character at the start of the string for the salt field.

So I feel like this is some sort of error in decoding the push header, perhaps failing to properly strip the quotes from salt="foo" or salt="" or similar.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

After a little bit of digging, here's what I learned about how these values arrive at the rust code:

  * When a sender sends a push message, it includes two headers relevant to the crypto: Encryption: salt=foo and Crypto-Key: dh=bar. Both of these headers contain b64url-encoded byte blobs, and they both use the HTTP standard syntax for key-value maps. That means that e.g. Encryption: salt="foo" is a perfectly valid header.
  * When the autopush server receives such a message, it extracts the Encryption and Crypto-Key headers from the push request, and puts them into fields on the outgoing mobile-platform-specific push notification system. They are the "enc" and "cryptokey" fields on the message respectively.
  * The push layers in android-components extract these fields and pass them unmodified down into the rust code.
  * The rust code attempts to parse ( https://github.com/mozilla/application-services/blob/356f7d129343a978426b50155d8f79e3b04aa7d1/components/push/src/crypto.rs#L112 ) the provided values as headers to extract the necessary fields.

The rust code does not appear to correctly handle quotes in these header values. It should. I'm going to try to push a failing test case to confirm this hypothesis.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Since it'll probably come up in conversation: I think it's unlikely that this issue could account for push messages going missing in send-tab, because AFAICT the FxA server never quotes the values that it puts in those headers. It seems more likely that these errors are from push messages sent by other services that (for whatever reason) include quotes in their outgoing push message headers.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I pushed https://github.com/mozilla/application-services/pull/3375, which I think confirms the hypothesis that this issue comes from failing to parse some valid header syntax. I don't have time to work further on this right now, but hopefully it'll be helpful as a starting point for whoever can pick this up.

**Comment by data-sync-user** [comment]
➤ Edouard Oger commented:

From Slack:

It seems that these headers should be cleaned up by the legacy autopush server (https://github.com/mozilla-services/autopush/blob/4cc12505d1f637cf16eff5f37e969358dfa202d6/autopush/utils.py#L377-L380), but I don't see any cleanup code in the autopush-rs server (https://github.com/mozilla-services/autopush-rs/blob/e73dff17e9a9909743fd57bbd9d6769789a455e1/autoendpoint/src/server/extractors/notification_headers.rs).

So either the legacy server is not cleaning up the headers properly, or the autopush-rs server is already in prod (I have no idea if that's the case)

**Comment by data-sync-user** [comment]
➤ Edouard Oger commented:

Server-side issue: https://github.com/mozilla-services/autopush/issues/1419

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

I suppose the good(?) news is that "= are never legit characters for an unpadded base64 so a simple filter to remove them would work fine. Slightly more clever would be to check the start and end of a string for them.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Multi-value HTTP hears are notoriously hard to parse, and I worry that some mis-behaving client could send unrelated garbage in this header that interferes with parsing. IMHO something should be responsible for parsing these fields according to the full rules for quoted values in HTTP headers and extracting the necessary parts, but I don't have a strong opinion on whether that should be client or server.

Naturally my incentives are for the server to do this work, because it's easier to ship fixed and updates to the server, but I'm open to the suggestion that it's not the best place :-)

Do we have documentation on what clients should expect from the fields of bridged push messages (like env and cryptokey mentioned above)? I wasn't able to find them in the autopush docs, only discussion on the HTTP endpoints.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

> I think it's unlikely that this issue could account for push messages going missing in send-tab 

As noted in https://github.com/mozilla-services/autopush/issues/1419, these headers are only used in the legacy 'aesgcm' encryption method, which is not used by FxA. So I think that more-or-less confirms that we can't blame any send-tab failures on this (but it's still worth fixing for overall product health).

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

> Do we have documentation on what clients should expect from the fields of bridged push messages (like env and cryptokey mentioned above)? I wasn't able to find them in the autopush docs, only discussion on the HTTP endpoints.

They're noted in older drafts of the ECE RFC ( https://tools.ietf.org/html/draft-ietf-httpbis-encryption-encoding-03#section-5.1 ), where they're quoted in the example.  Where things get wonky is that the older, more widely understood RFC2616 ( https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html ) doesn't quote header values, which leads to confusion. 

I suppose my suggestion that UA should at least consider accepting both is due to the fact that this data comes from outside of the apps immediate control and therefore should be suspect, but I'm a deeply paranoid programmer.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

> They're noted in older drafts of the ECE RFC, where they're quoted in the example

I mean something more specific here - IIUC our bridge server accepts these are HTTP headers, does some amount of normalization, and then passes them on as fields in a proprietary push message that depends on the bridged platform (APNS, Firebase, what-have-you). Do we have a doc with the expected schemas for those last-mile push messages from the bridge to the device? (Alternately, do I misunderstand the data flow here?)

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

I don't think you do misunderstand. I just don't believe that there's a doc that outlines what that flow should be, partly because it was semi-ad-hoc. 

That said, i did identify a bug in the header cleanup the python server was doing that I'm going to address in https://github.com/mozilla-services/autopush/issues/1419.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

IIUC, next step here is to keep an eye on the sentry errors as https://github.com/mozilla-services/autopush/issues/1419 goes to production and see if they reduce; we should also consider doing similar stripping on the client side for completeness.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Autopush 1.57.0 shipped to production today (2020-07-29) with https://github.com/mozilla-services/autopush/issues/1419 - we should be able to monitor https://sentry.prod.mozaws.net/operations/fenix/issues/8820593/ to see if it's resolved. Moving this issue to review.
