### ISSUE TITLE
RemoteTabsProvider.setLocalTabs fails with `PoisonError` after unrelated sync failures

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/uniffi-rs#923]
(sorry @Amejia481, I'm going to edit your initial bug comment here to add ongoing context; -@rfk)

## Current Status
As described in [this comment](https://github.com/mozilla/application-services/issues/4035#issuecomment-851102193), we think the issue here is that `SyncManager::do_sync` holds a `MutexGuard` for the tabs-store and logins-store for the duration of a sync. Any uncaught panic in the course of a sync will poison these mutexes, rendering the stores unusable even if the original error had nothing to do with tabs or logins.

In addition to fixing the underlying issues causing a panic during a sync (e.g. ref #4153) we should refactor things inside `SyncManager` so that it only holds the mutex for the tab store _while it is syncing tabs_, not for the whole duration of the sync.

- - -
The issue was addressed on AS `61.0.7` but it's happening again on AS `74.0.1`.

Sentry Fenix nightly https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8825532/
Fenix issue https://github.com/mozilla-mobile/fenix/issues/12162

![image](https://user-images.githubusercontent.com/773158/115598849-d9f74b00-a2a8-11eb-92a9-86d5228d8ecd.png)

**Stacktrace:**

    mozilla.appservices.remotetabs.RemoteTabProviderException: called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"
        at mozilla.appservices.remotetabs.rust.RustError.intoException(RustError.kt:4)
        at mozilla.appservices.remotetabs.RemoteTabsProvider.setLocalTabs(RemoteTabsProvider.kt:11)
        at mozilla.components.browser.storage.sync.RemoteTabsStorage$store$2.invokeSuspend(RemoteTabsStorage.kt:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

**Comment by data-sync-user** [comment]
➤ Christian Sadilek commented:

We're seeing a spike of this crash starting with yesterday's Fenix Nightly (Build #2015813067 Friday 5.28 @ 5:07PM). 

Here are A-C and Fenix commit ranges of this build relative to the previous one:
A-C: https://github.com/mozilla-mobile/android-components/compare/429f8390559bfdac7a01f10c81b4231cfe71fa68...3d76f03b56bd6df65112da8bc5699a30cbfcd7b0

Fenix: https://github.com/mozilla-mobile/fenix/compare/279d59897c6d613460eb992784979f18f7ad9cda...e0b410efdfe0f3422d836a45da01f5d7de5334a2

It does contain the A-S 77.0.1 upgrade but could also be a combination of things. Would appreciate some 👀 and happy to help debug this on Monday.

**Comment by data-sync-user** [comment]
➤ Christian Sadilek commented:

Original crash and spike: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8825532/
Possibly interesting new crash with similar cause: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/11490306

**Comment by data-sync-user** [comment]
➤ Andrew Sutherland commented:

I was experiencing this and was able to mitigate by signing out of sync by directly going to the kebab menu (three vertical dots in the lower right), going to settings and clicking on my sync account under "account" and signing out (disconnecting?).  Bringing up the URL bar UI would initiate a crash, so the key thing was avoiding pressing that.  For extra cross-referencing, I also reported this on the bug with the crash-status signature at https://bugzilla.mozilla.org/show_bug.cgi?id=1649808

**Comment by data-sync-user** [comment]
➤ Christian Sadilek commented:

These two started spiking at around the same time (caught and logged as infos):
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/11456952/
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8822116/

[INFO] ffi_support::error - Caught a panic calling rust code: "assertion failed: `(left != right)`\n  left: `Guid(\"8917d9c8b49c\")`,\n right: `Guid(\"8917d9c8b49c\")`"

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

This issue will likely block Fx 90 nightly from being promoted to Beta.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I'm taking a look at this today and trying to build a mental model of what's happening, which means I'm probably going to dump a few partially-collected thoughts in the bug in the meantime.

Unfortunately for us, Rust's `PoisonError` ( https://doc.rust-lang.org/std/sync/struct.PoisonError.html )` is a layer of indirection. It happens when you're trying to acquire a mutex, and indicates that at some point in the past some other thread panicked while holding that mutex. Since there can be no guarantees about the internal integrity of the data protected by the mutex after a panic, any further attempts to acquire the mutex will fail with this error.

So there must be some earlier underlying error that's happening, perhaps at lower volume, which is poisoning one of our mutexes and resulting in this failure for future attempts to use the underlying data.

The linked assertion failure ( https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8822116/ ) may be a good clue, so I'm going to start digging in there.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

[INFO] ffi_support::error - Caught a panic calling rust code: "assertion failed: `(left != right)`\n  left: `Guid(\"8917d9c8b49c\")`,\n right: `Guid(\"8917d9c8b49c\")`"This error message suggests a failing call to assert_ne!, which I figure we can't have too many of in non-test code. There are a couple of candidates in the new autofill code that look like they'd call assert_ne! in release code on some Guids:

  * One here in `apply_incoming_action` ( https://github.com/mozilla/application-services/blob/e67c3aab466ac833a14a5113e88bc4e720976371/components/autofill/src/sync/mod.rs#L380 )
  * One here in `plan_incoming` ( https://github.com/mozilla/application-services/blob/e67c3aab466ac833a14a5113e88bc4e720976371/components/autofill/src/sync/mod.rs#L336 )
  * One here in `common_change_guid` ( https://github.com/mozilla/application-services/blob/e67c3aab466ac833a14a5113e88bc4e720976371/components/autofill/src/sync/common.rs#L82 )

The fact that the spikes seem to heat up recently, may be a clue that the autofills ones are behind that particular issue.

**Comment by data-sync-user** [comment]
➤ Leif commented:

> ```
> [INFO] ffi_support::error - Caught a panic calling rust code: "assertion failed: (left != right)\n  left: Guid(\"8917d9c8b49c\"),\n right: Guid(\"8917d9c8b49c\")"
> ```
> 
> This error message suggests a failing call to assert_ne!, which I figure we can't have too many of in non-test code. There are a couple of candidates in the new autofill code that look like they'd call assert_ne! in release code on some Guids:
> 
> * One here in `apply_incoming_action` ( https://github.com/mozilla/application-services/blob/e67c3aab466ac833a14a5113e88bc4e720976371/components/autofill/src/sync/mod.rs#L380 )
> * One here in `plan_incoming` ( https://github.com/mozilla/application-services/blob/e67c3aab466ac833a14a5113e88bc4e720976371/components/autofill/src/sync/mod.rs#L336 )
> * One here in `common_change_guid` ( https://github.com/mozilla/application-services/blob/e67c3aab466ac833a14a5113e88bc4e720976371/components/autofill/src/sync/common.rs#L82 )
> 
> The fact that the spikes seem to heat up recently, may be a clue that the autofills ones are behind that particular issue.

You may well be onto something as I realized that the crash began to happen at first when I opened the bar and began to type. After that it just refused to open. Something to do with the autofill would definitely relate to being loaded when typing there and opening it so that makes sense. A credit card feature is new I know and a potential idea for things to check.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

> So there must be some earlier underlying error that's happening, perhaps at lower volume, which is poisoning one
> of our mutexes and resulting in this failure for future attempts to use the underlying data.

On this theory, I went looking in sentry for other errors containing Rust. There are a lot of variations on PoisonError, quite a few variations on this assertion failed: (left != right) Guid(...)`, and nothing else that I could see spiking the last couple of days. So A loose theory could be something like:

  * An assertion failing is panicking while attempting to sync autofill data.
  * This poisons one or more mutexes held by the syncmanager while it's syncing.
  * Other seemingly-unrelated code then starts to fail with a PoisonError when it tries to use those same mutexes.

I'll see if I can reproduce by adding some autofill data to my account.

L31FY are you able to reproduce this crash consistently? If so and if you have some time, I'm curious how it relates to the signed-in state of the browser:

  * Try signing out on your android device, does that stop it from crashing?
  * Try signing back in, does the crash start happening again?
  * Try disabling the syncing of creditcard and address data, does the crash still occur?

**Comment by data-sync-user** [comment]
➤ Leif commented:

> > So there must be some earlier underlying error that's happening, perhaps at lower volume, which is poisoning one
> > of our mutexes and resulting in this failure for future attempts to use the underlying data.
> 
> On this theory, I went looking in sentry for other errors containing Rust. There are a lot of variations on PoisonError, quite a few variations on this assertion failed: (left != right) Guid(...)`, and nothing else that I could see spiking the last couple of days. So A loose theory could be something like:
> 
> * An assertion failing is panicking while attempting to sync autofill data.
> * This poisons one or more mutexes held by the syncmanager while it's syncing.
> * Other seemingly-unrelated code then starts to fail with a PoisonError when it tries to use those same mutexes.
> 
> I'll see if I can reproduce by adding some autofill data to my account.
> 
> L31FY are you able to reproduce this crash consistently? If so and if you have some time, I'm curious how it relates to the signed-in state of the browser:
> 
> * Try signing out on your android device, does that stop it from crashing?
> * Try signing back in, does the crash start happening again?
> * Try disabling the syncing of creditcard and address data, does the crash still occur?

Signed out and it took marginally longer but still got a crash trying to browse or type so I expect signed back in would have the same results. I have even clean installed between this and tried without syncing yet but something seems to be up.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Ah, no worries - I was hoping that signing out would help, but thank for trying nonetheless!

**Comment by data-sync-user** [comment]
➤ Leif commented:

> Ah, no worries - I was hoping that signing out would help, but thank for trying nonetheless!

Well now it seems like as long as I'm not typing too much it's helping some. That top bar has some effect for sure. Clicking ok. Typing not so much. Maybe it's taking a minute to catch up.

**Comment by data-sync-user** [comment]
➤ B.J. Herbison commented:

Before I turned off Sync any page load would cause a crash. After I turned off Sync I was able to load pages but I still had one PoisonError crash today with Sync off. When I signed into Sync almost every action causes a crash again. I signed out again and now pages load without crashing again.

Don't blame everything on autofill. Most of my crashes with Sync on were from tapping pinned sites on the front page.

**Comment by data-sync-user** [comment]
➤ Leif commented:

> Before I turned off Sync any page load would cause a crash. After I turned off Sync I was able to load pages but I still had one PoisonError crash today with Sync off. When I signed into Sync almost every action causes a crash again. I signed out again and now pages load without crashing again.
> 
> Don't blame everything on autofill. Most of my crashes with Sync on were from tapping pinned sites on the front page.

It's seeming like a bit of a problem with both from what I'm getting but definitely one with sync causing any page load to crash first, then something with autofill causing an intermittent crash when typing maybe.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

> Don't blame everything on autofill. Most of my crashes with Sync on were from tapping pinned sites on the front page.

Just to expand on my thinking here a bit, I think we're seeing the crash manifest itself most frequently in the call to mozilla.appservices.remotetabs.RemoteTabsProvider.setLocalTabs because this call happens a lot

  * basically whenever you try to navigate somewhere in the browser, it triggers an event that updates the browser engine's session state, with triggers an event which notifies the synced-tabs listener, which calls setLocalTabs to try to update its copy of the browser's set of open tabs.

However, all access to the synced-tabs state is done through an `Arc<Mutex<TabStore>>` ( https://github.com/mozilla/application-services/blob/e67c3aab466ac833a14a5113e88bc4e720976371/components/tabs/ffi/src/lib.rs#L22 ). If any thread that is holding that Mutex panics for any reason, then all future attempts to call setLocalTabs will fail with the PoisonError seen in this bug.

The other thing that can take this Mutex is the sync-manager, in its `do_sync` method here ( https://github.com/mozilla/application-services/blob/e67c3aab466ac833a14a5113e88bc4e720976371/components/sync_manager/src/manager.rs#L334 ). AFAICT do_sync will acquire the protecting mutex for the store for every syncable data type, sync them all, then release all the mutexes at the end. So if there is a failing assertion that causes a panic while syncing any datatype, that will poison the store mutex for all datatypes. It just so happens that the tabs store is the one the user interacts with most often, so we see the resulting PoisonError surfaced there in volume.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

> AFAICT do_sync will acquire the protecting mutex for the store for every syncable data type

On further inspection, this isn't quite true - places and addresses don't have a mutex at this level so the syncmanager doesn't take them, but it does take the mutex for logins and tabs. Which would explain why we also sometimes see poison errors on the logins store ( https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/11490306/ ) but at a lower volume than for tabs.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

csadilek I'm looking for other evidence that this may be related to autofill stuff, was there new autofill functionality added or enabled in this recent build? Alternately, I wonder if the recent uplift of Bug 1713089 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1713089 ) has populated folks sync stores with more data in the last couple of days, which has started triggering some data consistency checks that were previously not getting hit at significant volume.

**Comment by data-sync-user** [comment]
➤ Leif commented:

> csadilek I'm looking for other evidence that this may be related to autofill stuff, was there new autofill functionality added or enabled in this recent build? Alternately, I wonder if the recent uplift of Bug 1713089 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1713089 ) has populated folks sync stores with more data in the last couple of days, which has started triggering some data consistency checks that were previously not getting hit at significant volume.

The only thing I for sure knew appears is the credit card thing but even turned off with no entries the crashing happens still. Once my cache was completely cleared and I did a force stop and reboot of the device, being signed out hasn't crashed in a decent while now.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

For coordination purposes, I've filed a separate issue for investigating the assertion failures: https://github.com/mozilla/application-services/issues/4153.

I think we now have a better understanding of why these surface as PoisonError in seemingly unrelated components, so I'm going to morph this issue into "SyncManager should not poison the store mutex for unrelated datatypes when a sync fails".

We're also going to try disabling the recently-enabled address syncing feature in Fenix Nightly, to help confirm whether this is the source of the problem, ref https://github.com/mozilla-mobile/fenix/pull/19726.

**Comment by data-sync-user** [comment]
➤ Christian Sadilek commented:

> We're also going to try disabling the recently-enabled address syncing feature in Fenix Nightly, to help confirm whether this is the source of the problem, ref mozilla-mobile/fenix#19726.

Yes, Autofill was enabled a week+ ago, but crashes only started on Friday. Looks like addresses sync landed on Friday in the build that caused the crash spike.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

(I've done what I can here for now, I don't think I'm the right person to actually attempt the proposed refactor of syncmanager; unassigning myself from the bug)

**Comment by data-sync-user** [comment]
➤ Leif commented:

> (I've done what I can here for now, I don't think I'm the right person to actually attempt the proposed refactor of syncmanager; unassigning myself from the bug)

Unless I can be of assistance (in which case please say so) or test something then it's over my head by quite a lot as to actually code a fix. Unfortunately I am more of a troubleshooting person. There looks to have been some good info gathered though for those who can use it for narrowing the actual causes of the issues.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Thanks for the offer - I expect someone from the Sync team will be able to work on this soon, but if we have any further ideas for testing we'll comment here in the bug.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

> We're also going to try disabling the recently-enabled address syncing feature in Fenix Nightly,
> to help confirm whether this is the source of the problem, ref mozilla-mobile/fenix#19726.

Following up here for completeness: we decided not to disable address syncing in Nightly, because we believe we found and fixed the underlying bug with https://github.com/mozilla-mobile/android-components/pull/10383. Initial results from Sentry seem promising, inasmuch as we're not seeing any crash reports for this issue with the new release version.

To check if you've got the fixed version, go to the "About Firefox Nightly" screen and look for "AS: 77.0.2"; previous versions would have had "AS: 77.0.1".

If you're still seeing crashes with "AS: 77.0.2", please let us know, it may be another bug which needs further triage.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

The critical errors were fixed.  And the long-term fix is the uniffi-cation of tabs component which is in-progress.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

🚩 Flag added

Resolved by Tabs uniffi-cation work for Fenix
