### ISSUE TITLE
noteHistoryMetadataObservation(): CHECK constraint failed: moz_places_metadata

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/uniffi-rs#967]
Fenix issue:
https://github.com/mozilla-mobile/fenix/issues/20123

```
mozilla.appservices.places.PlacesException: Error executing SQL: CHECK constraint failed: moz_places_metadata
at mozilla.appservices.places.RustError.intoException(RustError.kt:58)
at mozilla.appservices.places.PlacesWriterConnection.noteHistoryMetadataObservation(PlacesConnection.kt:1865)
at mozilla.components.browser.storage.sync.PlacesHistoryStorage.noteHistoryMetadataObservation$suspendImpl(PlacesHistoryStorage.kt:263)
at mozilla.components.browser.storage.sync.PlacesHistoryStorage.noteHistoryMetadataObservation(Unknown Source:0)
at org.mozilla.fenix.historymetadata.DefaultHistoryMetadataService$createMetadata$1.invokeSuspend(HistoryMetadataService.kt:77)
```

**Comment by data-sync-user** [comment]
➤ Sebastian Kaspari commented:

grigoryk and csadilek are both out this week.

**Comment by data-sync-user** [comment]
➤ Christian Sadilek commented:

This should only be active in debug builds. See https://github.com/mozilla-mobile/fenix/issues/20123#issuecomment-866285339 for how to disable. We'll look into it when we're back 😀
